export const ROLES = [
    { value: "select role", label: "Select Role"},
    { value: "admin", label: "Admin" },
    { value: "user", label: "User" },
    { value: "moderator", label: "Moderator" },
    { value: "traveler", label: "Traveler" },
];

export const COUNTRIES = [
    { value: "empty", label: " - Select Country" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguilla", label: "Anguilla" },
    { value: "Antigua & Barbuda", label: "Antigua & Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Aruba", label: "Aruba" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bermuda", label: "Bermuda" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia & Herzegovina", label: "Bosnia & Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "British Virgin Islands", label: "British Virgin Islands" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Cape Verde", label: "Cape Verde" },
    { value: "Cayman Islands", label: "Cayman Islands" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Colombia", label: "Colombia" },
    { value: "Congo", label: "Congo" },
    { value: "Cook Islands", label: "Cook Islands" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Cote D Ivoire", label: "Cote D Ivoire" },
    { value: "Croatia", label: "Croatia" },
    { value: "Cruise Ship", label: "Cruise Ship" },
    { value: "Cuba", label: "Cuba" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    { value: "Denmark", label: "Denmark" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Falkland Islands", label: "Falkland Islands" },
    { value: "Faroe Islands", label: "Faroe Islands" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "French Polynesia", label: "French Polynesia" },
    { value: "French West Indies", label: "French West Indies" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Germany", label: "Germany" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Greece", label: "Greece" },
    { value: "Greenland", label: "Greenland" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea Bissau", label: "Guinea Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Isle of Man", label: "Isle of Man" },
    { value: "Israel", label: "Israel" },
    { value: "Italy", label: "Italy" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japan", label: "Japan" },
    { value: "Jersey", label: "Jersey" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyz Republic", label: "Kyrgyz Republic" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Macau", label: "Macau" },
    { value: "Macedonia", label: "Macedonia" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mexico", label: "Mexico" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "Netherlands Antilles", label: "Netherlands Antilles" },
    { value: "New Caledonia", label: "New Caledonia" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palestine", label: "Palestine" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Qatar", label: "Qatar" },
    { value: "Reunion", label: "Reunion" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Pierre & Miquelon", label: "Saint Pierre & Miquelon" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Satellite", label: "Satellite" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Korea", label: "South Korea" },
    { value: "Spain", label: "Spain" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "St Kitts & Nevis", label: "St Kitts & Nevis" },
    { value: "St Lucia", label: "St Lucia" },
    { value: "St Vincent", label: "St Vincent" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Swaziland", label: "Swaziland" },
    { value: "Sweden", label: "Sweden" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Syria", label: "Syria" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Timor L'Este", label: "Timor L'Este" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad & Tobago", label: "Trinidad & Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Turks & Caicos", label: "Turks & Caicos" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Virgin Islands (US)", label: "Virgin Islands (US)" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
];

export const LANGUAGES = [
    { value: "select", label: " - Select Language" },
    { value: "af", label: "Afrikaans" },
    { value: "sq", label: "Albanian shqip" },
    { value: "am", label: "Amharic አማርኛ" },
    { value: "ar", label: "Arabic العربية" },
    { value: "an", label: "Aragonese aragonés" },
    { value: "hy", label: "Armenian հայերեն" },
    { value: "ast", label: "Asturian asturianu" },
    { value: "az", label: "Azerbaijani azərbaycan dili" },
    { value: "eu", label: "Basque euskara" },
    { value: "be", label: "Belarusian беларуская" },
    { value: "bn", label: "Bengali বাংলা" },
    { value: "bs", label: "Bosnian bosanski" },
    { value: "br", label: "Breton brezhoneg" },
    { value: "bg", label: "Bulgarian български" },
    { value: "ca", label: "Catalan català" },
    { value: "ckb", label: "Central Kurdish کوردی (دەستنوسی عەرەبی)" },
    { value: "zh", label: "Chinese 中文" },
    { value: "zh-HK", label: "Chinese (Hong Kong) 中文（香港）" },
    { value: "zh-CN", label: "Chinese (Simplified) 中文（简体）" },
    { value: "zh-TW", label: "Chinese (Traditional) 中文（繁體）" },
    { value: "co", label: "Corsican" },
    { value: "hr", label: "Croatian hrvatski" },
    { value: "cs", label: "Czech čeština" },
    { value: "da", label: "Danish dansk" },
    { value: "nl", label: "Dutch Nederlands" },
    { value: "be-nl", label: "Dutch Belgium" },
    { value: "en", label: "English" },
    { value: "en-AU", label: "English (Australia)" },
    { value: "en-CA", label: "English (Canada)" },
    { value: "en-IN", label: "English (India)" },
    { value: "en-NZ", label: "English (New Zealand)" },
    { value: "en-ZA", label: "English (South Africa)" },
    { value: "en-GB", label: "English (United Kingdom)" },
    { value: "en-US", label: "English (United States)" },
    { value: "eo", label: "Esperanto esperanto" },
    { value: "et", label: "Estonian eesti" },
    { value: "fo", label: "Faroese føroyskt" },
    { value: "fil", label: "Filipino" },
    { value: "fi", label: "Finnish suomi" },
    { value: "fr", label: "French français" },
    { value: "fr-CA", label: "French (Canada) français (Canada)" },
    { value: "fr-FR", label: "French (France) français (France)" },
    { value: "fr-CH", label: "French (Switzerland) français (Suisse)" },
    { value: "gl", label: "Galician galego" },
    { value: "ka", label: "Georgian ქართული" },
    { value: "de", label: "German Deutsch" },
    { value: "de-AT", label: "German (Austria) Deutsch (Österreich)" },
    { value: "de-DE", label: "German (Germany) Deutsch (Deutschland)" },
    { value: "de-LI", label: "German (Liechtenstein) Deutsch (Liechtenstein)" },
    { value: "de-CH", label: "German (Switzerland) Deutsch (Schweiz)" },
    { value: "el", label: "Greek Ελληνικά" },
    { value: "gn", label: "Guarani" },
    { value: "gu", label: "Gujarati ગુજરાતી" },
    { value: "ha", label: "Hausa" },
    { value: "haw", label: "Hawaiian ʻŌlelo Hawaiʻi" },
    { value: "he", label: "Hebrew עברית" },
    { value: "hi", label: "Hindi हिन्दी" },
    { value: "hu", label: "Hungarian magyar" },
    { value: "is", label: "Icelandic íslenska" },
    { value: "id", label: "Indonesian Indonesia" },
    { value: "ia", label: "Interlingua" },
    { value: "ga", label: "Irish Gaeilge" },
    { value: "it", label: "Italian italiano" },
    { value: "it-IT", label: "Italian (Italy) italiano (Italia)" },
    { value: "it-CH", label: "Italian (Switzerland) italiano (Svizzera)" },
    { value: "ja", label: "Japanese 日本語" },
    { value: "kn", label: "Kannada ಕನ್ನಡ" },
    { value: "kk", label: "Kazakh қазақ тілі" },
    { value: "km", label: "Khmer ខ្មែរ" },
    { value: "ko", label: "Korean 한국어" },
    { value: "ku", label: "Kurdish Kurdî" },
    { value: "ky", label: "Kyrgyz кыргызча" },
    { value: "lo", label: "Lao ລາວ" },
    { value: "la", label: "Latin" },
    { value: "lv", label: "Latvian latviešu" },
    { value: "ln", label: "Lingala lingála" },
    { value: "lt", label: "Lithuanian lietuvių" },
    { value: "mk", label: "Macedonian македонски" },
    { value: "ms", label: "Malay Bahasa Melayu" },
    { value: "ml", label: "Malayalam മലയാളം" },
    { value: "mt", label: "Maltese Malti" },
    { value: "mr", label: "Marathi मराठी" },
    { value: "mn", label: "Mongolian монгол" },
    { value: "ne", label: "Nepali नेपाली" },
    { value: "no", label: "Norwegian norsk" },
    { value: "nb", label: "Norwegian Bokmål norsk bokmål" },
    { value: "nn", label: "Norwegian Nynorsk nynorsk" },
    { value: "oc", label: "Occitan" },
    { value: "or", label: "Oriya ଓଡ଼ିଆ" },
    { value: "om", label: "Oromo Oromoo" },
    { value: "ps", label: "Pashto پښتو" },
    { value: "fa", label: "Persian فارسی" },
    { value: "pl", label: "Polish polski" },
    { value: "pt", label: "Portuguese português" },
    { value: "pt-BR", label: "Portuguese (Brazil) português (Brasil)" },
    { value: "pt-PT", label: "Portuguese (Portugal) português (Portugal)" },
    { value: "pa", label: "Punjabi ਪੰਜਾਬੀ" },
    { value: "qu", label: "Quechua" },
    { value: "ro", label: "Romanian română" },
    { value: "mo", label: "Romanian (Moldova) română (Moldova)" },
    { value: "rm", label: "Romansh rumantsch" },
    { value: "ru", label: "Russian русский" },
    { value: "gd", label: "Scottish Gaelic" },
    { value: "sr", label: "Serbian српски" },
    { value: "sh", label: "Serbo Croatian" },
    { value: "sn", label: "Shona chiShona" },
    { value: "sd", label: "Sindhi" },
    { value: "si", label: "Sinhala සිංහල" },
    { value: "sk", label: "Slovak slovenčina" },
    { value: "sl", label: "Slovenian slovenščina" },
    { value: "so", label: "Somali Soomaali" },
    { value: "st", label: "Southern Sotho" },
    { value: "es", label: "Spanish español" },
    { value: "es-AR", label: "Spanish (Argentina) español (Argentina)" },
    { value: "es-419", label: "Spanish (Latin America) español (Latinoamérica)" },
    { value: "es-MX", label: "Spanish (Mexico) español (México)" },
    { value: "es-ES", label: "Spanish (Spain) español (España)" },
    { value: "es-US", label: "Spanish (United States) español (Estados Unidos)" },
    { value: "su", label: "Sundanese" },
    { value: "sw", label: "Swahili Kiswahili" },
    { value: "sv", label: "Swedish svenska" },
    { value: "tg", label: "Tajik тоҷикӣ" },
    { value: "ta", label: "Tamil தமிழ்" },
    { value: "tt", label: "Tatar" },
    { value: "te", label: "Telugu తెలుగు" },
    { value: "th", label: "Thai ไทย" },
    { value: "ti", label: "Tigrinya ትግርኛ" },
    { value: "to", label: "Tongan lea fakatonga" },
    { value: "tr", label: "Turkish Türkçe" },
    { value: "tk", label: "Turkmen" },
    { value: "tw", label: "Twi" },
    { value: "uk", label: "Ukrainian українська" },
    { value: "ur", label: "Urdu اردو" },
    { value: "ug", label: "Uyghur" },
    { value: "uz", label: "Uzbek o‘zbek" },
    { value: "vi", label: "Vietnamese Tiếng Việt" },
    { value: "wa", label: "Walloon wa" },
    { value: "cy", label: "Welsh Cymraeg" },
    { value: "fy", label: "Western Frisian" },
    { value: "xh", label: "Xhosa" },
    { value: "yi", label: "Yiddish" },
    { value: "yo", label: "Yoruba Èdè Yorùbá" },
    { value: "zu", label: "Zulu isiZulu" },
];

export const CURRENCIES = [
    { value: "empty", label: " - Select Currency" },
    { value: "AFA", label: "Afghan Afghani" },
    { value: "ALL", label: "Albanian Lek" },
    { value: "DZD", label: "Algerian Dinar" },
    { value: "AOA", label: "Angolan Kwanza" },
    { value: "ARS", label: "Argentine Peso" },
    { value: "AMD", label: "Armenian Dram" },
    { value: "AWG", label: "Aruban Florin" },
    { value: "AUD", label: "Australian Dollar" },
    { value: "AZN", label: "Azerbaijani Manat" },
    { value: "BSD", label: "Bahamian Dollar" },
    { value: "BHD", label: "Bahraini Dinar" },
    { value: "BDT", label: "Bangladeshi Taka" },
    { value: "BBD", label: "Barbadian Dollar" },
    { value: "BYR", label: "Belarusian Ruble" },
    { value: "BEF", label: "Belgian Franc" },
    { value: "BZD", label: "Belize Dollar" },
    { value: "BMD", label: "Bermudan Dollar" },
    { value: "BTN", label: "Bhutanese Ngultrum" },
    { value: "BTC", label: "Bitcoin" },
    { value: "BOB", label: "Bolivian Boliviano" },
    { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
    { value: "BWP", label: "Botswanan Pula" },
    { value: "BRL", label: "Brazilian Real" },
    { value: "GBP", label: "British Pound Sterling" },
    { value: "BND", label: "Brunei Dollar" },
    { value: "BGN", label: "Bulgarian Lev" },
    { value: "BIF", label: "Burundian Franc" },
    { value: "KHR", label: "Cambodian Riel" },
    { value: "CAD", label: "Canadian Dollar" },
    { value: "CVE", label: "Cape Verdean Escudo" },
    { value: "KYD", label: "Cayman Islands Dollar" },
    { value: "XOF", label: "CFA Franc BCEAO" },
    { value: "XAF", label: "CFA Franc BEAC" },
    { value: "XPF", label: "CFP Franc" },
    { value: "CLP", label: "Chilean Peso" },
    { value: "CLF", label: "Chilean Unit of Account" },
    { value: "CNY", label: "Chinese Yuan" },
    { value: "COP", label: "Colombian Peso" },
    { value: "KMF", label: "Comorian Franc" },
    { value: "CDF", label: "Congolese Franc" },
    { value: "CRC", label: "Costa Rican Colón" },
    { value: "HRK", label: "Croatian Kuna" },
    { value: "CUC", label: "Cuban Convertible Peso" },
    { value: "CZK", label: "Czech Republic Koruna" },
    { value: "DKK", label: "Danish Krone" },
    { value: "DJF", label: "Djiboutian Franc" },
    { value: "DOP", label: "Dominican Peso" },
    { value: "XCD", label: "East Caribbean Dollar" },
    { value: "EGP", label: "Egyptian Pound" },
    { value: "ERN", label: "Eritrean Nakfa" },
    { value: "EEK", label: "Estonian Kroon" },
    { value: "ETB", label: "Ethiopian Birr" },
    { value: "EUR", label: "Euro" },
    { value: "FKP", label: "Falkland Islands Pound" },
    { value: "FJD", label: "Fijian Dollar" },
    { value: "GMD", label: "Gambian Dalasi" },
    { value: "GEL", label: "Georgian Lari" },
    { value: "DEM", label: "German Mark" },
    { value: "GHS", label: "Ghanaian Cedi" },
    { value: "GIP", label: "Gibraltar Pound" },
    { value: "GRD", label: "Greek Drachma" },
    { value: "GTQ", label: "Guatemalan Quetzal" },
    { value: "GNF", label: "Guinean Franc" },
    { value: "GYD", label: "Guyanaese Dollar" },
    { value: "HTG", label: "Haitian Gourde" },
    { value: "HNL", label: "Honduran Lempira" },
    { value: "HKD", label: "Hong Kong Dollar" },
    { value: "HUF", label: "Hungarian Forint" },
    { value: "ISK", label: "Icelandic Króna" },
    { value: "INR", label: "Indian Rupee" },
    { value: "IDR", label: "Indonesian Rupiah" },
    { value: "IRR", label: "Iranian Rial" },
    { value: "IQD", label: "Iraqi Dinar" },
    { value: "ILS", label: "Israeli New Sheqel" },
    { value: "ITL", label: "Italian Lira" },
    { value: "JMD", label: "Jamaican Dollar" },
    { value: "JPY", label: "Japanese Yen" },
    { value: "JOD", label: "Jordanian Dinar" },
    { value: "KZT", label: "Kazakhstani Tenge" },
    { value: "KES", label: "Kenyan Shilling" },
    { value: "KWD", label: "Kuwaiti Dinar" },
    { value: "KGS", label: "Kyrgystani Som" },
    { value: "LAK", label: "Laotian Kip" },
    { value: "LVL", label: "Latvian Lats" },
    { value: "LBP", label: "Lebanese Pound" },
    { value: "LSL", label: "Lesotho Loti" },
    { value: "LRD", label: "Liberian Dollar" },
    { value: "LYD", label: "Libyan Dinar" },
    { value: "LTC", label: "Litecoin" },
    { value: "LTL", label: "Lithuanian Litas" },
    { value: "MOP", label: "Macanese Pataca" },
    { value: "MKD", label: "Macedonian Denar" },
    { value: "MGA", label: "Malagasy Ariary" },
    { value: "MWK", label: "Malawian Kwacha" },
    { value: "MYR", label: "Malaysian Ringgit" },
    { value: "MVR", label: "Maldivian Rufiyaa" },
    { value: "MRO", label: "Mauritanian Ouguiya" },
    { value: "MUR", label: "Mauritian Rupee" },
    { value: "MXN", label: "Mexican Peso" },
    { value: "MDL", label: "Moldovan Leu" },
    { value: "MNT", label: "Mongolian Tugrik" },
    { value: "MAD", label: "Moroccan Dirham" },
    { value: "MZM", label: "Mozambican Metical" },
    { value: "MMK", label: "Myanmar Kyat" },
    { value: "NAD", label: "Namibian Dollar" },
    { value: "NPR", label: "Nepalese Rupee" },
    { value: "ANG", label: "Netherlands Antillean Guilder" },
    { value: "TWD", label: "New Taiwan Dollar" },
    { value: "NZD", label: "New Zealand Dollar" },
    { value: "NIO", label: "Nicaraguan Córdoba" },
    { value: "NGN", label: "Nigerian Naira" },
    { value: "KPW", label: "North Korean Won" },
    { value: "NOK", label: "Norwegian Krone" },
    { value: "OMR", label: "Omani Rial" },
    { value: "PKR", label: "Pakistani Rupee" },
    { value: "PAB", label: "Panamanian Balboa" },
    { value: "PGK", label: "Papua New Guinean Kina" },
    { value: "PYG", label: "Paraguayan Guarani" },
    { value: "PEN", label: "Peruvian Nuevo Sol" },
    { value: "PHP", label: "Philippine Peso" },
    { value: "PLN", label: "Polish Zloty" },
    { value: "QAR", label: "Qatari Rial" },
    { value: "RON", label: "Romanian Leu" },
    { value: "RUB", label: "Russian Ruble" },
    { value: "RWF", label: "Rwandan Franc" },
    { value: "SVC", label: "Salvadoran Colón" },
    { value: "WST", label: "Samoan Tala" },
    { value: "STD", label: "São Tomé and Príncipe Dobra" },
    { value: "SAR", label: "Saudi Riyal" },
    { value: "RSD", label: "Serbian Dinar" },
    { value: "SCR", label: "Seychellois Rupee" },
    { value: "SLL", label: "Sierra Leonean Leone" },
    { value: "SGD", label: "Singapore Dollar" },
    { value: "SKK", label: "Slovak Koruna" },
    { value: "SBD", label: "Solomon Islands Dollar" },
    { value: "SOS", label: "Somali Shilling" },
    { value: "ZAR", label: "South African Rand" },
    { value: "KRW", label: "South Korean Won" },
    { value: "SSP", label: "South Sudanese Pound" },
    { value: "XDR", label: "Special Drawing Rights" },
    { value: "LKR", label: "Sri Lankan Rupee" },
    { value: "SHP", label: "St. Helena Pound" },
    { value: "SDG", label: "Sudanese Pound" },
    { value: "SRD", label: "Surinamese Dollar" },
    { value: "SZL", label: "Swazi Lilangeni" },
    { value: "SEK", label: "Swedish Krona" },
    { value: "CHF", label: "Swiss Franc" },
    { value: "SYP", label: "Syrian Pound" },
    { value: "TJS", label: "Tajikistani Somoni" },
    { value: "TZS", label: "Tanzanian Shilling" },
    { value: "THB", label: "Thai Baht" },
    { value: "TOP", label: "Tongan Pa'anga" },
    { value: "TTD", label: "Trinidad & Tobago Dollar" },
    { value: "TND", label: "Tunisian Dinar" },
    { value: "TRY", label: "Turkish Lira" },
    { value: "TMT", label: "Turkmenistani Manat" },
    { value: "UGX", label: "Ugandan Shilling" },
    { value: "UAH", label: "Ukrainian Hryvnia" },
    { value: "AED", label: "United Arab Emirates Dirham" },
    { value: "UYU", label: "Uruguayan Peso" },
    { value: "USD", label: "US Dollar" },
    { value: "UZS", label: "Uzbekistan Som" },
    { value: "VUV", label: "Vanuatu Vatu" },
    { value: "VEF", label: "Venezuelan Bolívar" },
    { value: "VND", label: "Vietnamese Dong" },
    { value: "YER", label: "Yemeni Rial" },
    { value: "ZMK", label: "Zambian Kwacha" },
    { value: "ZWL", label: "Zimbabwean Dollar" },
];
